services:
  mysql:
    image: mysql:8.3
    container_name: deliveryapp-mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: delivery_db
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  api:
    build: 
      context: ../../../..
      dockerfile: src/main/resources/container/Dockerfile
    ports:
      - "8080:8080"    
    environment:
      SPRING_PROFILES_ACTIVE: dev
    
    restart: unless-stopped
    
    networks:
      - app-networks

    container_name: deliveryapp-api

volumes:
  mysql_data:

networks:
  app-networks:
    driver: bridge