version: '3.9'

services:
  mysql:
    image: mysql:8.3
    container_name: deliveryapp-mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: delivery_db
      MYSQL_USER: test
      MYSQL_PASWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
