name: Build and Deploy

on:
  workflow_dispatch:

# on:
#   push:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: |
          cd delivery-api
          mvn clean package
      - name: Deploy to server
        run: scp delivery-api/target/*.jar user@server:/app/

      
